#!/usr/bin/env python3
"""Build company_pages_data.json from structured company research."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from company_extra_data import EXTRA

OUT = Path(__file__).with_name("company_pages_data.json")
COMMON = [
    "Medical, dental, and vision insurance",
    "401(k) with company match",
    "Equity / RSU or stock options (4-year vest typical)",
    "Parental leave and wellness programs",
]


def co(
    name, color, resume_slug, tier, focus, location, meta, comp, comp_note, h1b,
    highlight, fit, pros, cons, interview, jobs, profile, tags, benefits=None, target_apps=None,
):
    return {
        "name": name, "color": color, "resume_slug": resume_slug, "tier": tier,
        "focus": focus, "location": location, "meta": meta, "comp": comp,
        "comp_note": comp_note, "h1b": h1b, "highlight": highlight, "fit": fit,
        "pros": pros, "cons": cons, "benefits": benefits or COMMON, "interview": interview,
        "jobs": jobs, "profile": profile, "tags": tags, "target_apps": target_apps or [],
    }


COMPANIES = {
    "anthropic": co(
        "Anthropic", "#c85f31", "Anthropic", "S-Tier", "Platform / Service Infra Engineering",
        "San Francisco, CA - ~45 min from San Ramon",
        ["Frontier AI - Claude", "H1B confirmed", "No layoffs", "Staff+ target"],
        [["$318K", "Base"], ["$233K", "Stock/yr"], ["$555K", "Median TC"], ["$890K", "Top reported"]],
        "Source: Levels.fyi, Jan 2026. Lead SWE median = $759K TC.",
        "Confirmed sponsor. Ask early at recruiter screen.",
        "Highest-paying match for your profile. Senior SWE median $555K; Lead = $759K.",
        "Platform role at Anthropic = your Credit Karma Portals Framework role.",
        ["Top-tier TC ($555K median Senior)", "Direct match to platform framework ownership",
         "Frontier AI mission", "H1B confirmed; actively growing", "Rewards real infra depth"],
        ["Very high coding bar", "Job links expire quickly", "In-office/hybrid in SF",
         "Values round requires AI safety prep"],
        ["5-6 rounds: recruiter, coding (2x), system design, infra design, values",
         "Coding: Hard LeetCode + distributed systems",
         "System design: deployment pipeline, service mesh, observability at scale",
         "Infra design: service registry, Consul, health checks",
         "Read Anthropic core views; only trust @anthropic.com emails"],
        [{"title": "Staff Software Engineer, Platform", "id": "5157847008",
          "url": "https://boards.greenhouse.io/anthropic/jobs/5157847008",
          "fit": "Platform framework ownership, TypeScript/Scala/Node.js, data contracts, distributed systems."}],
        "Staff-level Software Engineer with 17+ years building platform infrastructure and distributed backend systems. At Credit Karma, designed and own the Portal Provider framework relied on by 90%+ of portals clients. MS CS, ASU 2021.",
        ["Scala", "TypeScript", "Java", "Kafka", "Kubernetes", "Platform Engineering", "Finagle"],
        target_apps=[{"role": "Staff Software Engineer, Platform", "id": "5157847008", "status": "Not started", "date": "-", "url": "https://boards.greenhouse.io/anthropic/jobs/5157847008"}],
    ),
    "openai": co(
        "OpenAI", "#10a37f", "Openai", "S-Tier", "Platform / Backend Infrastructure",
        "San Francisco, CA - ~45 min from San Ramon",
        ["ChatGPT / GPT-4o", "H1B confirmed", "Actively growing", "Senior/Staff target"],
        [["$300K", "Base"], ["$500K", "PPU/yr"], ["$800K", "Typical TC"], ["$1.28M", "Top reported"]],
        "PPUs tied to profitability. Best shot at $800K+ without promotion.",
        "Confirmed sponsor - verify at recruiter screen; only @openai.com contacts.",
        "Highest-TC opportunity in the entire list. Apply in parallel with Anthropic.",
        "Backend/platform teams build APIs and infra all product teams depend on.",
        ["Highest typical TC (~$800K Senior)", "Platform work maps to your background",
         "Rapid growth and equity upside", "H1B confirmed sponsor"],
        ["Intense competition for platform roles", "Mission alignment expected",
         "PPU value tied to profitability", "Hard LeetCode + distributed systems rounds"],
        ["5-6 rounds: recruiter, coding (2x), system design, infra design, values",
         "Coding: Hard LeetCode - distributed systems and concurrency",
         "System design: API gateway, distributed job scheduler, container orchestration",
         "Infra: 100K RPS, 99.99% uptime - circuit breakers, rate limiting",
         "Lead with Finagle EOL + 100% uptime modernization story"],
        [{"title": "Senior Staff Backend Software Engineer, API Platform", "id": "API-Platform-SWE",
          "url": "https://openai.com/careers/senior-staff-backend-software-engineer-api-platform-san-francisco/",
          "fit": "API platform at Credit Karma, distributed systems, TypeScript/Scala/Java."}],
        "Senior Staff Software Engineer with 17+ years in platform infrastructure and API systems. Owns Finagle-based web framework at Credit Karma. MS CS, ASU 2021.",
        ["Java", "Scala", "TypeScript", "Kafka", "Kubernetes", "Platform Engineering"],
        target_apps=[{"role": "Senior Staff Backend SWE, API Platform", "id": "API-Platform-SWE", "status": "Not started", "date": "-", "url": "https://openai.com/careers/senior-staff-backend-software-engineer-api-platform-san-francisco/"}],
    ),
    "xai": co(
        "xAI", "#000000", "Xai", "High-upside", "Grok / Platform Engineering",
        "Palo Alto / San Francisco",
        ["Pre-IPO AI startup", "Small team, high ownership", "Fast 2-3 round process"],
        [["$250K-$400K+", "Base"], ["Significant", "Pre-IPO equity"], ["-", "TC varies"], ["High", "Equity upside"]],
        "Pre-IPO equity could be very valuable; base lower than mega-caps.",
        "Confirm sponsorship at recruiter screen.",
        "Small team, high ownership. Platform engineering matches Finagle framework ownership.",
        "Thrives in small, high-impact teams moving fast.",
        ["Very fast interview process", "High ownership on Grok", "Pre-IPO equity upside", "Platform experience relevant"],
        ["H1B process less proven", "Long hours likely", "Less predictable TC", "Smaller brand stability"],
        ["2-3 rounds total", "Technical screen: coding + system design",
         "Loop: deep system design, coding, culture fit",
         "Lead with MakeMyTrip payments + Credit Karma platform framework"],
        [{"title": "Senior Grok Engineer", "id": "4823149007", "url": "https://job-boards.greenhouse.io/xai/jobs/4823149007", "fit": "Scala/TypeScript/Java platform engineering."},
         {"title": "Software Engineer - Grok Voice", "id": "4720475007", "url": "https://job-boards.greenhouse.io/xai/jobs/4720475007", "fit": "Distributed backend, event-driven architecture."}],
        "Staff Software Engineer with 17+ years in platform infrastructure. Architected Portal Provider at Credit Karma. MS CS, ASU 2021.",
        ["Java", "Scala", "TypeScript", "Kafka", "Kubernetes", "Platform Engineering"],
        target_apps=[
            {"role": "Senior Grok Engineer", "id": "4823149007", "status": "Not started", "date": "-", "url": "https://job-boards.greenhouse.io/xai/jobs/4823149007"},
            {"role": "Software Engineer - Grok Voice", "id": "4720475007", "status": "Not started", "date": "-", "url": "https://job-boards.greenhouse.io/xai/jobs/4720475007"},
        ],
    ),
    "nvidia": co(
        "NVIDIA", "#76b900", "Nvidia", "S-Tier", "Cloud Platform Engineering",
        "Santa Clara, CA - ~30 min from San Ramon",
        ["Glassdoor #1 Tech 2026", "3,244 H1B FY2025", "No major layoffs", "IC4 target"],
        [["$250K", "Base"], ["$129K", "Stock/yr"], ["$369K", "Median TC"], ["$608K+", "IC6 top"]],
        "TC below $500K at IC4 - negotiate stock.",
        "3,244 H1B approvals FY2025; dedicated immigration counsel.",
        "Scala + Kafka + Cassandra + K8s maps to NGC Cloud Platform.",
        "Cross-team shared infrastructure = platform multiplier work NVIDIA values.",
        ["Glassdoor #1 tech 2026", "Strong H1B volume", "30 min commute", "AI/cloud tailwind", "Flat org"],
        ["Median TC ($369K) below target at IC4", "Need IC5 or equity negotiation", "Santa Clara not SF"],
        ["4-5 rounds: recruiter, technical (coding + system design), hiring manager",
         "Coding: Medium-Hard LeetCode", "System design: distributed cache, multi-tenant cloud infra",
         "Emphasize platform ownership and open-source"],
        [{"title": "Senior Cloud Platform Software Engineer", "id": "JR2003876",
          "url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/JR2003876",
          "fit": "Kubernetes, AWS/GCP/Azure, distributed microservices, platform design."}],
        "Senior Software Engineer with 17+ years in cloud platform and distributed infrastructure. MS CS, ASU 2021.",
        ["Kubernetes", "Docker", "AWS", "GCP", "Java", "Kafka", "Distributed Systems"],
        target_apps=[{"role": "Senior Cloud Platform Software Engineer", "id": "JR2003876", "status": "Not started", "date": "-", "url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/JR2003876"}],
    ),
    "servicenow": co(
        "ServiceNow", "#62d84e", "Servicenow", "S-Tier", "AI Platform Engineering",
        "Santa Clara, CA - ~30 min (closest target)",
        ["Glassdoor Top 3 Tech 2026", "H1B active enterprise sponsor", "Stable", "Staff target"],
        [["$200K", "Base"], ["$200K", "Stock/yr"], ["$400-550K", "TC range"], ["$700K+", "Principal/Staff"]],
        "Staff/Principal path to $700K+.",
        "Active enterprise sponsor with established immigration process.",
        "Closest target geographically. Glassdoor Top 3, no major layoffs.",
        "Java platform + cross-team framework = ServiceNow platform multiplier needs.",
        ["Shortest commute (~30 min)", "Very stable employer", "Deep Java match (17 years)",
         "TC can hit $500K at Staff", "Enterprise H1B process"],
        ["Enterprise SaaS pace slower than AI labs", "Base lower than AI labs", "Less exciting brand"],
        ["4-5 rounds: recruiter, coding (2x), system design, hiring manager",
         "Coding: Medium LeetCode - Java preferred", "System design: multi-tenant workflow engine",
         "Lead with platform framework ownership at Credit Karma"],
        [{"title": "Staff Software Engineer, Backend Java", "id": "744000086443311",
          "url": "https://careers.servicenow.com/jobs/744000086443311/staff-software-engineer-backend-java/",
          "fit": "17+ years Java/Spring/Hibernate, REST/GraphQL, event-driven microservices."}],
        "Staff Java Backend Software Engineer with 17+ years in enterprise distributed systems. MS CS, ASU 2021.",
        ["Java", "Spring Boot", "Hibernate", "Kafka", "Cassandra", "Microservices"],
        target_apps=[{"role": "Staff Software Engineer, Backend Java", "id": "744000086443311", "status": "Not started", "date": "-", "url": "https://careers.servicenow.com/jobs/744000086443311/staff-software-engineer-backend-java/"}],
    ),
    "confluent": co(
        "Confluent", "#172B4D", "Confluent", "A-Tier", "Kafka / Streaming Platform",
        "Mountain View, CA - ~40 min",
        ["Company behind Apache Kafka", "H1B active sponsor", "No major layoffs", "L5 target"],
        [["$220K", "Base"], ["$297K", "Stock/yr"], ["$517K", "Median TC"], ["$733K", "L6a top"]],
        "L5 median $517K hits $500K target.",
        "Active sponsor - confirm at recruiter screen.",
        "Kafka at 5 companies - almost unmatched candidate profile.",
        "8+ years Kafka across MakeMyTrip, Wenova, Pearson, Nordstrom, Credit Karma.",
        ["Best Kafka depth story", "L5 median hits TC target", "Work with Kafka experts", "Strong equity upside"],
        ["Narrower domain (streaming only)", "Mountain View commute", "Deep Kafka domain round"],
        ["4-5 rounds: recruiter, coding (2x), system design, Kafka domain",
         "System design: event streaming platform, multi-tenant Kafka cluster",
         "Kafka domain: consumer groups, exactly-once, compaction, replication"],
        [{"title": "Senior Software Engineer - Apache Kafka", "id": "15812054",
          "url": "https://careers.confluent.io/jobs/15812054-senior-software-engineer-apache-kafka",
          "fit": "Kafka at 5 companies spanning fintech, ecommerce, edtech."}],
        "Senior Software Engineer with deep Apache Kafka production experience across 5 companies. MS CS, ASU 2021.",
        ["Apache Kafka", "Java", "Scala", "Event-Driven Architecture", "Distributed Systems"],
        target_apps=[{"role": "Senior Software Engineer - Apache Kafka", "id": "15812054", "status": "Not started", "date": "-", "url": "https://careers.confluent.io/jobs/15812054-senior-software-engineer-apache-kafka"}],
    ),
    "databricks": co(
        "Databricks", "#ff3621", "Databricks", "A-Tier", "Data + AI Platform Engineering",
        "San Francisco, CA - ~50 min",
        ["Data+AI leader", "H1B confirmed", "No major layoffs", "L5/Staff target"],
        [["$220K", "Base L5"], ["$215K", "Stock/yr"], ["$435K", "Median TC"], ["$1.68M", "L7 top"]],
        "Pre-IPO equity upside. L6 ($700K+) within 18 months is realistic.",
        "Confirmed on careers page - case-by-case at interview stage.",
        "Pre-IPO equity upside. Written largely in Scala - direct Credit Karma relevance.",
        "Scala + Spark + Kubernetes + distributed data systems - your exact stack.",
        ["Scala/Kafka/Cassandra stack match", "Pre-IPO equity upside", "Multiple Staff roles",
         "Strong engineering culture", "H1B confirmed"],
        ["L5 median TC below $500K day-one", "Greenhouse security code friction", "SF commute ~50 min"],
        ["5-6 rounds: recruiter, coding (2x), system design, domain/architecture, HM",
         "Coding: Medium-Hard LeetCode; Scala/Java preferred",
         "Domain: Spark execution model, shuffle, partitions, fault tolerance"],
        [{"title": "Staff Software Engineer - Distributed Data Systems", "id": "6937001002",
          "url": "https://www.databricks.com/company/careers/open-positions/6937001002",
          "fit": "Cassandra, CouchBase, Elasticsearch, multi-datacenter architectures."}],
        "Senior/Staff Software Engineer specializing in distributed data systems. Scala, Java, Kafka, Kubernetes. MS CS, ASU 2021.",
        ["Distributed Systems", "Cassandra", "Kafka", "Java", "Scala", "Kubernetes"],
    ),
    "stripe": co(
        "Stripe", "#635bff", "Stripe", "A-Tier", "Payments Infrastructure",
        "San Francisco, CA - ~45 min",
        ["$91.5B valuation", "H1B active fintech sponsor", "~500 open roles", "L4 target"],
        [["$230K", "Base"], ["$197K", "Stock/yr"], ["$427K", "Median TC"], ["$1.08M", "L5 top"]],
        "Push for L4+ or Senior title.",
        "Active fintech sponsor with experienced immigration team.",
        "MakeMyTrip payment revamp is your superpower - lead with it in every Stripe conversation.",
        "Myntra 500M carts + MakeMyTrip payment revamp + Wavecrest PCI = rare payments depth.",
        ["Best payments domain story", "Strong engineering brand", "SF office", "H1B-friendly fintech sponsor"],
        ["L4 median TC below $500K", "Referral helps significantly", "Extremely high correctness bar"],
        ["4-5 rounds: recruiter, 2 coding, system design, HM/culture",
         "System design: payment processing, distributed rate limiter, fraud detection",
         "Values: correctness and fault tolerance in financial systems"],
        [{"title": "Software Engineer, Payments", "id": "7529787",
          "url": "https://stripe.com/jobs/listing/software-engineer-payments/7529787",
          "fit": "Myntra/Flipkart 500M carts, MakeMyTrip payment revamp, Wavecrest PCI."}],
        "Senior Software Engineer with 17+ years in payments and distributed backend systems. MS CS, ASU 2021.",
        ["Java", "Kafka", "Cassandra", "PCI DSS", "Payments", "Microservices"],
        target_apps=[{"role": "Software Engineer, Payments", "id": "7529787", "status": "Not started", "date": "-", "url": "https://stripe.com/jobs/listing/software-engineer-payments/7529787"}],
    ),
    "google": co(
        "Google", "#4285f4", "Google", "A-Tier", "Cloud AI / Payments Infrastructure",
        "Mountain View, CA - ~40 min",
        ["18-yr Glassdoor best place", "#1 H1B volume (1,050+)", "L5 target", "L6 in 18 mo"],
        [["$225K", "Base"], ["$200K", "Stock/yr"], ["$425K", "Median TC L5"], ["$2.24M", "L9 top"]],
        "Push for L5 not L4. L6 path = $700K-$1.2M.",
        "#1 volume sponsor - 1,050+ FY2025 approvals. Most reliable H1B path.",
        "Cloud AI and Google Pay teams growing despite layoffs elsewhere.",
        "17 years distributed systems + Myntra/MMT payments = Cloud Financial Services match.",
        ["Most reliable H1B sponsor", "L5/L6 promotion path to $700K+", "Cloud + Pay teams hiring",
         "18-year Glassdoor best place", "Brand and resume signal"],
        ["Longest process (3-4 months)", "Hardest coding bar", "L5 median below target day-one", "Org uncertainty from layoffs"],
        ["5-7 rounds: recruiter, phone screen, 4-5 onsite",
         "Coding: Hard LeetCode - 100+ problems via NeetCode",
         "System design: global payments, sharding, consistency",
         "Push for L5 - 17 yrs + MS CS should land L5 not L4"],
        [{"title": "Software Engineer, Google Cloud Financial Services", "id": "121405674409075398",
          "url": "https://careers.google.com/jobs/results/121405674409075398/",
          "fit": "FinTech + cloud: MakeMyTrip payments, Credit Karma platform, GCP, Kafka."}],
        "Senior Software Engineer at intersection of cloud infrastructure and financial systems. MS CS, ASU 2021.",
        ["Java", "Scala", "Kafka", "GCP", "AWS", "Payments", "Kubernetes"],
        target_apps=[{"role": "Software Engineer, Google Cloud Financial Services", "id": "121405674409075398", "status": "Not started", "date": "-", "url": "https://careers.google.com/jobs/results/121405674409075398/"}],
    ),
    "snowflake": co(
        "Snowflake", "#29b5e8", "Snowflake", "A-Tier", "Data Cloud Platform",
        "San Mateo, CA - ~30 min",
        ["Data cloud leader", "H1B active sponsor", "Stable", "MTS2 target"],
        [["$220-290K", "Base"], ["$300-550K", "Stock/yr"], ["$420-640K", "TC range"], ["$640K+", "Senior Staff"]],
        "TC range hits $500K target. Tied with ServiceNow for closest commute.",
        "Active sponsor - enterprise-scale immigration support.",
        "30 min commute + Java/Scala platform work + TC in target range.",
        "Multi-tenant data cloud needs distributed systems + Java/Scala.",
        ["30 min from San Ramon", "TC $420K-$640K hits target", "Java/Scala platform work", "Stable employer"],
        ["Less brand excitement vs AI labs", "Data warehouse domain learning curve", "Deep Java concurrency tests"],
        ["4-5 rounds: recruiter, coding (2x), system design, hiring manager",
         "System design: multi-tenant query engine, distributed metadata store",
         "Domain: Virtual Warehouses, Cloud Services, Storage architecture"],
        [{"title": "Senior Software Engineer - Cloud Services", "id": "SNCOUS683A",
          "url": "https://careers.snowflake.com/us/en", "fit": "Cloud services, Cassandra, Kubernetes, Java/Scala."}],
        "Senior Software Engineer with 17+ years in cloud services and distributed data infrastructure. MS CS, ASU 2021.",
        ["Java", "Scala", "Cassandra", "Kubernetes", "AWS", "GCP"],
        target_apps=[{"role": "Senior Software Engineer - Cloud Services", "id": "SNCOUS683A", "status": "Not started", "date": "-", "url": "https://careers.snowflake.com/us/en"}],
    ),
    "netflix": co(
        "Netflix", "#e50914", "Netflix", "A-Tier", "Backend / Distributed Systems",
        "Los Gatos, CA - ~35 min",
        ["300M+ subscribers", "H1B active sponsor", "Stable", "L5 target"],
        [["$300-450K", "All-in base"], ["Your choice", "Salary vs stock"], ["$550K", "L5 median"], ["$619K", "Top L5"]],
        "Unique all-in comp model - choose salary/stock split annually.",
        "Confirmed active sponsor - median H1B salary $226K FY2025.",
        "Finagle framework ownership at CK = Netflix gateway/platform engineering.",
        "Scala/Java backend at 10M+ RPS scale. Kafka at 5 companies.",
        ["L5 median $550K hits target", "Unique comp flexibility", "Freedom/responsibility culture",
         "Scala-heavy backend match", "Autonomy for senior engineers"],
        ["High performance bar", "Sink or swim culture", "Los Gatos not SF", "No traditional perf reviews"],
        ["4-5 rounds: recruiter, coding (2x), system design, culture",
         "System design: streaming CDN, high-throughput event pipeline",
         "Read Netflix Culture Deck before onsite"],
        [{"title": "Distributed Systems Engineer 5 - Cloud Gateway", "id": "790315481039",
          "url": "https://jobs.netflix.com/jobs/790315481039", "fit": "Finagle ownership, Kafka/Cassandra at scale."}],
        "Senior/Staff Distributed Systems Engineer. Owns Finagle-based web framework at Credit Karma. MS CS, ASU 2021.",
        ["Scala", "Java", "Finagle", "Kafka", "Cassandra", "Distributed Systems"],
        benefits=["Unlimited PTO (culture of responsibility)", "Full medical/dental/vision for employee + dependents",
                  "Annual comp choice: salary vs stock options", "No formal vacation accrual"],
        target_apps=[{"role": "Distributed Systems Engineer 5 - Cloud Gateway", "id": "790315481039", "status": "Not started", "date": "-", "url": "https://jobs.netflix.com/jobs/790315481039"}],
    ),
    "uber": co(
        "Uber", "#000000", "Uber", "A-Tier", "Java Platform / Payments",
        "San Francisco, CA - ~45 min",
        ["Global mobility platform", "H1B active sponsor", "Stable post-2020", "Senior Staff target"],
        [["$198-224K", "Base"], ["~$150K", "Stock/yr est"], ["$350-375K", "TC est"], ["$500K+", "Senior Staff"]],
        "Push for Senior Staff to hit $500K+.",
        "Large company, established process - confirm at recruiter screen.",
        "Java Platform team = structurally identical to Credit Karma Portals Framework role.",
        "Builds core Java microservices framework all Uber engineering teams run on.",
        ["Java Platform role is exact CK parallel", "SF office", "Payments teams value MMT/Myntra",
         "Good leverage for negotiations elsewhere"],
        ["Senior TC likely below $500K target", "Must push for Senior Staff", "Lower base than peers"],
        ["4-5 rounds: recruiter, coding (2x), system design, HM/bar raiser",
         "System design: surge pricing, distributed rate limiter, real-time dispatch",
         "Push for Senior or Senior Staff - do not accept SWE II"],
        [{"title": "Staff Software Engineer (Backend) - Java Platform", "id": "156244",
          "url": "https://www.uber.com/global/en/careers/list/156244/", "fit": "Finagle platform ownership, 17+ years Java."}],
        "Staff Backend Software Engineer with deep Java platform expertise. MS CS, ASU 2021.",
        ["Java", "Spring Boot", "Kafka", "Platform Engineering", "Finagle"],
        target_apps=[{"role": "Staff Software Engineer (Backend) - Java Platform", "id": "156244", "status": "Not started", "date": "-", "url": "https://www.uber.com/global/en/careers/list/156244/"}],
    ),
    "spacex": co(
        "SpaceX", "#005288", "Spacex", "Mission-driven", "Backend / Distributed Systems (Starlink)",
        "Hawthorne CA / Redmond WA / remote",
        ["Starlink ground software", "Long hours culture", "Mission-first engineering"],
        [["$180-260K", "Base"], ["Stock", "SpaceX equity"], ["-", "TC varies"], ["-", "Pre-IPO upside"]],
        "Lower base than Bay Area tech; equity in private SpaceX.",
        "Confirm sponsorship - mission-critical roles may have flexibility.",
        "Kafka/Cassandra at scale, multi-DC architecture applicable to Starlink ground software.",
        "High-reliability distributed backend for Starlink infrastructure.",
        ["Unique mission impact", "Deep distributed systems engineering", "Pre-IPO equity upside", "Engineering-first culture"],
        ["Base comp well below target", "Long hours reported", "Hawthorne commute if not remote", "H1B less established"],
        ["Recruiter screen (30 min)", "Technical phone screen (1hr): DS&A, system design",
         "Onsite loop (4-5 hrs): coding, distributed systems design, HM/mission",
         "Lead with MakeMyTrip multi-DC architecture"],
        [{"title": "Sr. Software Engineer - Backend / Distributed Systems (Starlink)", "id": "8300183002",
          "url": "https://job-boards.greenhouse.io/spacex/jobs/8300183002", "fit": "Kafka/Cassandra, multi-datacenter for Starlink."}],
        "Staff Software Engineer with 17+ years building distributed backend systems at scale. MS CS, ASU 2021.",
        ["Java", "Python", "Kafka", "Cassandra", "Kubernetes", "Distributed Systems"],
        target_apps=[{"role": "Sr. SWE - Backend / Distributed Systems (Starlink)", "id": "8300183002", "status": "Not started", "date": "-", "url": "https://job-boards.greenhouse.io/spacex/jobs/8300183002"}],
    ),
}

APPLICATIONS = {
    "databricks": [
        {"role": "Staff SWE - Distributed Data Systems", "id": "6937001002", "status": "Submitted", "date": "2026-06-04", "url": "https://job-boards.greenhouse.io/embed/job_app?for=databricks&token=6937001002"},
        {"role": "Staff SWE - Distributed Data Systems", "id": "5646855002", "status": "Submitted", "date": "2026-06-04", "url": "https://job-boards.greenhouse.io/embed/job_app?for=databricks&token=5646855002"},
        {"role": "Sr. Staff SWE - Data Platform", "id": "7823561002", "status": "Submitted", "date": "2026-06-04", "url": "https://job-boards.greenhouse.io/embed/job_app?for=databricks&token=7823561002"},
        {"role": "Staff SWE - Backend", "id": "5408888002", "status": "Submitted", "date": "2026-06-04", "url": "https://job-boards.greenhouse.io/embed/job_app?for=databricks&token=5408888002"},
        {"role": "Staff SWE - Database Engine Internals", "id": "5646866002", "status": "In progress", "date": "2026-06-05", "url": "https://job-boards.greenhouse.io/embed/job_app?for=databricks&token=5646866002"},
        {"role": "Staff SWE - IAM", "id": "7994801002", "status": "Pending", "date": "-", "url": "https://job-boards.greenhouse.io/embed/job_app?for=databricks&token=7994801002"},
        {"role": "Senior Staff SWE - Security Infrastructure", "id": "7274908002", "status": "Pending", "date": "-", "url": "https://job-boards.greenhouse.io/embed/job_app?for=databricks&token=7274908002"},
    ],
}


def main():
    companies = {}
    questions_path = Path(__file__).with_name("company_latest_questions.json")
    latest = {}
    if questions_path.exists():
        raw = json.loads(questions_path.read_text(encoding="utf-8"))
        latest = {k: v for k, v in raw.items() if not k.startswith("_")}

    for slug, co in COMPANIES.items():
        merged = dict(co)
        if slug in EXTRA:
            merged["snapshot"] = {
                "company_type": EXTRA[slug]["company_type"],
                "salary_range": EXTRA[slug]["salary_range"],
                "growth_note": EXTRA[slug]["growth_note"],
                "perks": EXTRA[slug]["perks"],
            }
            merged["how_to_crack"] = EXTRA[slug]["how_to_crack"]
            merged["benefits"] = EXTRA[slug]["perks"]
        merged["latest_questions"] = latest.get(slug, [])
        companies[slug] = merged
    payload = {"companies": companies, "applications": APPLICATIONS}
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
