# Company snapshot + how-to-crack prep data (merged into company_pages_data.json)

EXTRA = {
    "anthropic": {
        "company_type": "Private (venture-backed). Last valued ~$60B+ (2025). No IPO announced; high growth potential if AI market holds.",
        "salary_range": "Senior SWE Bay Area: $450K-$650K TC typical; Staff/Lead $700K-$890K+ (Levels.fyi 2026).",
        "growth_note": "Fastest-growing frontier AI lab after OpenAI. Equity upside if IPO or secondary liquidity events.",
        "perks": [
            "Premium medical/dental/vision",
            "401(k) with company match",
            "Catered lunches and snacks (SF office)",
            "Generous equity grants (4-year vest, 25%/yr)",
            "16+ weeks parental leave",
            "Learning stipend / conference budget",
            "Hybrid/in-office SF with flexible arrangements (team-dependent)",
        ],
        "how_to_crack": {
            "style": "Structured loop, high bar. Mix of hard coding, infra/system design, and values alignment.",
            "rounds": "5-6: recruiter screen -> 2x coding -> system design -> infra/platform design -> values/culture.",
            "coding": "Heavy LeetCode (Hard). Also distributed-systems flavored problems. Less pure puzzle, more real-world constraints at Staff level.",
            "prep_plan": [
                "4-6 weeks LeetCode: NeetCode 150 + 30 Hard (graphs, DP, concurrency)",
                "Prep 3 system designs: deployment pipeline, service mesh, observability platform",
                "Prep 2 infra designs: service registry, multi-tenant auth at scale",
                "Read Anthropic core views + Responsible Scaling Policy",
                "Practice Finagle EOL + 100% uptime modernization story (5 min + deep dive)",
                "Mock 1 values round: AI safety, long-term impact, intellectual humility",
            ],
        },
    },
    "openai": {
        "company_type": "Private (capped-profit structure). Massive revenue growth from ChatGPT/API. IPO timing unclear; PPUs tied to profitability.",
        "salary_range": "Senior/Staff Bay Area: $700K-$900K+ TC typical; top reports $1.28M (Levels.fyi 2026).",
        "growth_note": "Category leader in generative AI. PPU equity can appreciate rapidly with revenue growth.",
        "perks": [
            "Top-tier compensation (base + PPUs)",
            "Full medical/dental/vision + mental health",
            "401(k) match",
            "Catered meals (SF campus)",
            "Equity via Profit Participation Units (PPUs)",
            "Parental leave and fertility benefits",
            "Hybrid SF office",
        ],
        "how_to_crack": {
            "style": "Similar to Anthropic: rigorous, mission-aware, infra-heavy for platform roles.",
            "rounds": "5-6: recruiter -> 2x coding -> system design -> infra design -> mission/values.",
            "coding": "Hard LeetCode + concurrency/distributed systems. Expect follow-ups on production tradeoffs.",
            "prep_plan": [
                "LeetCode Hard daily (6 weeks): focus concurrency, thread pools, rate limiters",
                "Design: API gateway at 100K RPS, distributed job scheduler, canary deploy system",
                "Read OpenAI mission charter and preparedness framework",
                "Prepare 3 STAR stories on platform ownership under SLA pressure",
                "Practice explaining Finagle migration without downtime",
                "Study circuit breakers, backpressure, idempotency for API platform round",
            ],
        },
    },
    "xai": {
        "company_type": "Private (Elon Musk). Pre-IPO; part of X ecosystem. Very high upside, very high risk.",
        "salary_range": "Senior engineer: $250K-$400K base + significant pre-IPO equity. TC varies widely.",
        "growth_note": "Small team scaling Grok. Equity could be valuable if xAI exits or grows with X integration.",
        "perks": [
            "Large pre-IPO equity grants",
            "Small team = high ownership",
            "Fast decision-making",
            "Medical/dental/vision (standard startup package)",
            "401(k) (verify at offer stage)",
            "Palo Alto / SF office",
        ],
        "how_to_crack": {
            "style": "Fast, lean loop. Less process than FAANG. Depth and speed matter more than polish.",
            "rounds": "2-3 total: technical screen (1hr) -> virtual loop (2-3 hrs) coding + system design + culture.",
            "coding": "Medium-Hard LeetCode plus practical system thinking. May skew practical over pure LC.",
            "prep_plan": [
                "2 weeks focused LC: 40 Medium, 15 Hard (arrays, graphs, system design basics)",
                "Prepare end-to-end system stories: MakeMyTrip payments + CK platform framework",
                "Practice whiteboarding a rate-limited API in 45 min",
                "Read about Grok product and xAI mission before culture chat",
                "Emphasize ownership, speed, and shipping under ambiguity",
            ],
        },
    },
    "nvidia": {
        "company_type": "Public (NASDAQ: NVDA). AI boom drove massive market cap growth. RSU liquidity is excellent.",
        "salary_range": "IC4 Senior Bay Area: $300K-$450K TC; IC5/IC6 $500K-$650K+ (Levels.fyi 2026).",
        "growth_note": "Public stock with strong AI tailwind. RSUs are liquid; less lottery than pre-IPO.",
        "perks": [
            "RSU grants + refresh cycles",
            "ESPP (employee stock purchase plan)",
            "401(k) with generous match",
            "On-site cafes and snacks (Santa Clara campus)",
            "Excellent medical/dental/vision",
            "Parental leave and backup childcare",
            "GPU employee purchase discounts",
        ],
        "how_to_crack": {
            "style": "Traditional big-tech loop. Balanced coding + system design. Flat culture.",
            "rounds": "4-5: recruiter -> 2-3 technical (coding + design) -> hiring manager.",
            "coding": "Medium-Hard LeetCode. Java/C++ common. Clean code and communication scored.",
            "prep_plan": [
                "3-4 weeks LC: NeetCode 75 + company tagged Medium/Hard",
                "System design: distributed cache, multi-tenant cloud infra, telemetry pipeline",
                "Highlight open-source and platform multiplier work",
                "Prepare Kubernetes + multi-cloud stories from CK",
                "Research NGC Cloud Platform if applying to cloud roles",
            ],
        },
    },
    "servicenow": {
        "company_type": "Public (NYSE: NOW). Enterprise SaaS leader. Stable growth, predictable RSUs.",
        "salary_range": "Senior/Staff Bay Area: $400K-$550K TC; Principal $600K-$700K+ (Levels.fyi 2026).",
        "growth_note": "Steady public comp. AI platform push creates new high-impact teams.",
        "perks": [
            "RSU equity program with refresh",
            "401(k) match + ESPP",
            "Free snacks and cafes (Santa Clara HQ)",
            "Strong medical/dental/vision",
            "Generous PTO + parental leave",
            "Hybrid work (3 days in office typical)",
            "Learning and certification reimbursement",
        ],
        "how_to_crack": {
            "style": "Enterprise tech loop. Java-heavy. Emphasis on reliability and clean design.",
            "rounds": "4-5: recruiter -> 2x coding -> system design -> hiring manager.",
            "coding": "Medium LeetCode. Java preferred. Idiomatic Spring/Java code appreciated.",
            "prep_plan": [
                "2-3 weeks LC Medium (Java solutions out loud)",
                "Design: multi-tenant workflow engine, notification platform, SDK for internal teams",
                "Lead with CK platform framework = ServiceNow platform multiplier parallel",
                "Prep Spring Boot, microservices, and HA patterns",
                "Practice explaining tradeoffs for enterprise customers (uptime, backward compat)",
            ],
        },
    },
    "confluent": {
        "company_type": "Public (NASDAQ: CFLT). Kafka company. Stock volatile but liquid RSUs.",
        "salary_range": "L5 Senior Bay Area: $480K-$580K TC median; L6 Staff $650K-$733K+ (Levels.fyi 2026).",
        "growth_note": "Public with strong streaming/data tailwind. RSU refresh helps total comp.",
        "perks": [
            "RSU equity + refresh grants",
            "401(k) match",
            "Free lunch/snacks (Mountain View office)",
            "Medical/dental/vision",
            "Parental leave",
            "Kafka Summit / training access",
            "Hybrid-friendly",
        ],
        "how_to_crack": {
            "style": "Strong domain round on Kafka. Coding is solid but not Google-hard.",
            "rounds": "4-5: recruiter -> 2x coding -> system design -> Kafka domain/culture.",
            "coding": "Medium LeetCode, Java preferred. Correctness and clarity over speed.",
            "prep_plan": [
                "2 weeks LC Medium + review Kafka internals deeply",
                "Study: consumer groups, rebalancing, exactly-once, compaction, ISR, replication",
                "Design: multi-tenant Kafka cluster, event streaming platform, CDC pipeline",
                "Prepare 'Kafka at 5 companies' narrative with specific failure stories",
                "Read Confluent blog on cloud control plane architecture",
                "Mock domain round: explain a production Kafka incident you resolved",
            ],
        },
    },
    "databricks": {
        "company_type": "Private (pre-IPO). Last private rounds ~$43B+ valuation. IPO widely expected; major equity upside.",
        "salary_range": "L5 Senior/Staff Bay Area: $380K-$500K TC; L6 Staff $650K-$850K+ (Levels.fyi 2026).",
        "growth_note": "Pre-IPO equity is the main upside bet. Strong data+AI market position.",
        "perks": [
            "Pre-IPO equity (likely RSUs at IPO)",
            "401(k) match",
            "Catered lunches (SF / Mountain View offices)",
            "Premium medical/dental/vision",
            "Parental leave + wellness stipend",
            "Learning budget and conference travel",
            "Hybrid SF / MV offices",
        ],
        "how_to_crack": {
            "style": "Structured loop with Spark/distributed-systems domain round. Scala/Java friendly.",
            "rounds": "5-6: recruiter -> 2x coding -> system design -> domain/architecture -> hiring manager.",
            "coding": "Medium-Hard LeetCode. Arrays, graphs, DS problems. Staff may get more practical coding.",
            "prep_plan": [
                "3-4 weeks LC: Medium/Hard mix + review Scala syntax if rusty",
                "Study Spark: execution model, shuffle, partitions, fault tolerance, Catalyst",
                "Design: distributed job scheduler, real-time pipeline, multi-tenant cluster manager",
                "Prepare CK Scala + Kafka + Cassandra stories mapped to Runtime/Data teams",
                "Review Delta Lake basics and lakehouse architecture",
                "Practice explaining multi-DC payment architecture from MakeMyTrip",
            ],
        },
    },
    "stripe": {
        "company_type": "Private (~$91.5B valuation, 2025). IPO rumors but no date. Late-stage private with strong revenue.",
        "salary_range": "L4 Bay Area: $380K-$480K TC; L5 $550K-$750K+ (Levels.fyi 2026). Push for Senior/L4+ title.",
        "growth_note": "Late-stage private. Equity valuable at current valuation; liquidity via secondaries possible.",
        "perks": [
            "Competitive base + equity (RSU/options)",
            "401(k) match",
            "Premium medical/dental/vision",
            "Catered lunches (SF office)",
            "Generous parental leave",
            "Remote-friendly teams (role-dependent)",
            "$5K+ annual learning stipend",
            "Wellness reimbursement",
        ],
        "how_to_crack": {
            "style": "High correctness bar. 'Move fast, don't break payments.' Practical coding + deep system design.",
            "rounds": "4-5: recruiter -> 2x coding -> system design -> HM/culture.",
            "coding": "Medium LeetCode. Emphasis on clean code, edge cases, and explaining tradeoffs.",
            "prep_plan": [
                "2-3 weeks LC Medium + focus on correctness and test cases",
                "Design: payment processing pipeline, idempotency keys, distributed rate limiter, fraud detection",
                "Lead every answer with MakeMyTrip payment revamp (multi-DC, 50% latency cut)",
                "Study PCI basics, idempotency, exactly-once payment semantics",
                "Prepare Myntra 500M carts / sharding story for scale questions",
                "Read Stripe engineering blog on reliability",
            ],
        },
    },
    "google": {
        "company_type": "Public (NASDAQ: GOOGL). Mega-cap, highly liquid RSUs. Most predictable equity.",
        "salary_range": "L5 SWE Bay Area: $400K-$500K TC; L6 Staff $700K-$1.2M (Levels.fyi 2026).",
        "growth_note": "Public RSUs with refresh. L5->L6 promotion is the path to $700K+.",
        "perks": [
            "Free meals at Bay Area campuses (famous perk)",
            "RSU grants + semi-annual refresh",
            "401(k) match + mega backdoor Roth options",
            "ESPP discount",
            "Excellent medical/dental/vision",
            "Generous parental leave (18-22 weeks)",
            "On-site gyms, massages, shuttles (campus-dependent)",
        ],
        "how_to_crack": {
            "style": "Classic Google loop. Hardest LC bar in this list. Googleyness behavioral round.",
            "rounds": "5-7: recruiter -> phone screen -> 4-5 onsite (coding, system design, Googleyness, team match).",
            "coding": "Hard LeetCode only. 100+ problems recommended. Graphs, DP, strings are core.",
            "prep_plan": [
                "6-8 weeks: NeetCode 150 + 50 extra Hard (start early - longest timeline)",
                "System design: Google-scale search index, Maps sharding, global payments",
                "Prep 5 Googleyness STAR stories (humility, collaboration, ambiguity)",
                "Negotiate level upfront: push L5 with 17 yrs + MS CS",
                "Target Cloud AI or Google Pay teams specifically",
                "Use interview warmup on leetcode.com/google top questions",
            ],
        },
    },
    "snowflake": {
        "company_type": "Public (NYSE: SNOW). Data cloud leader. RSUs liquid; stock has been volatile.",
        "salary_range": "MTS2 Senior Bay Area: $420K-$640K TC; Senior Staff $640K+ (Levels.fyi 2026).",
        "growth_note": "Public company with enterprise moat. RSU refresh supports comp growth.",
        "perks": [
            "RSU equity + refresh",
            "401(k) match",
            "Free snacks/drinks (San Mateo HQ)",
            "Medical/dental/vision",
            "Parental leave",
            "Hybrid San Mateo office (~30 min from San Ramon)",
            "Employee stock purchase plan",
        ],
        "how_to_crack": {
            "style": "Solid enterprise loop. Java concurrency depth. Multi-tenant system design.",
            "rounds": "4-5: recruiter -> 2x coding -> system design -> hiring manager.",
            "coding": "Medium-Hard LeetCode, Java preferred. GC, concurrency, memory model questions common.",
            "prep_plan": [
                "3 weeks LC + Java concurrency review (JMM, thread pools, CompletableFuture)",
                "Design: multi-tenant query engine, metadata store, cloud storage layer",
                "Read Snowflake architecture blog (Virtual Warehouses, Cloud Services, Storage)",
                "Prepare distributed systems stories from CK + MakeMyTrip",
                "Practice explaining CAP tradeoffs in warehouse scheduling context",
            ],
        },
    },
    "netflix": {
        "company_type": "Public (NASDAQ: NFLX). Streaming giant. Unique all-in comp model.",
        "salary_range": "L5 Senior Bay Area: $500K-$620K all-in (you choose salary vs stock split annually).",
        "growth_note": "Public stock. High cash option available. Performance culture - no weak performers.",
        "perks": [
            "All-in comp (choose salary vs stock options each year)",
            "Unlimited PTO (responsible use culture)",
            "Full medical/dental/vision for you + dependents",
            "No 401(k) match traditionally - offset by higher cash comp",
            "Freedom and responsibility culture",
            "Los Gatos campus with free snacks",
        ],
        "how_to_crack": {
            "style": "Culture-heavy. Strong system design. Expect failure-mode thinking in distributed systems.",
            "rounds": "4-5: recruiter -> 2x coding -> system design -> culture ('freedom and responsibility').",
            "coding": "Medium-Hard LeetCode, Java/Scala. Interviewers probe edge cases and failure scenarios.",
            "prep_plan": [
                "3 weeks LC + read Netflix Culture Deck cover to cover",
                "Design: CDN cache invalidation, high-throughput event pipeline, global session store",
                "Prepare Finagle framework ownership story (direct Netflix parallel)",
                "Practice explaining tradeoffs when things fail at 10M+ RPS",
                "Show learning agility across Scala, Java, Kotlin, TypeScript",
                "Be ready for 'tell me about a time you made a bold decision' stories",
            ],
        },
    },
    "uber": {
        "company_type": "Public (NYSE: UBER). Profitable mobility platform. Liquid RSUs.",
        "salary_range": "Senior SWE Bay Area: $350K-$400K TC; Senior Staff $500K-$600K+ (Levels.fyi 2026).",
        "growth_note": "Public, stable post-restructuring. Push Senior Staff for $500K+ target.",
        "perks": [
            "RSU equity + refresh",
            "401(k) match",
            "Uber credits / mobility perks",
            "Medical/dental/vision",
            "Free lunch (SF office, team-dependent)",
            "Hybrid SF office",
            "Parental leave",
        ],
        "how_to_crack": {
            "style": "Standard big-tech loop with bar raiser. Real-time systems flavor in design.",
            "rounds": "4-5: recruiter -> 2x coding -> system design -> HM/bar raiser.",
            "coding": "Medium LeetCode, Java/Go. Distributed failure scenarios emphasized.",
            "prep_plan": [
                "2-3 weeks LC Medium",
                "Design: surge pricing engine, dispatch matching, distributed rate limiter",
                "Lead with Java Platform parallel to CK Portals Framework",
                "Prepare Myntra/MMT payments stories for fares/payments teams",
                "Negotiate level: refuse SWE II, target Senior Staff",
                "Practice explaining on-call/incident response at scale",
            ],
        },
    },
    "spacex": {
        "company_type": "Private (SpaceX). Starlink driving revenue. Pre-IPO; long-hours culture. Mission-driven.",
        "salary_range": "Sr SWE: $180K-$260K base + SpaceX stock. TC below Bay Area tech norms.",
        "growth_note": "Pre-IPO equity in SpaceX. Potential massive upside but illiquid for years.",
        "perks": [
            "SpaceX stock (private, illiquid)",
            "Medical/dental/vision",
            "401(k) (verify match at offer)",
            "On-site rocket factory / mission exposure",
            "No free lunch culture like Google - mission is the perk",
            "Long hours expected (60+ hr weeks reported)",
        ],
        "how_to_crack": {
            "style": "Rigorous, mission-aligned. Deep distributed systems. Less LC grind, more engineering depth.",
            "rounds": "Recruiter (30m) -> phone screen (1hr DS&A) -> onsite loop (4-5 hrs coding + DS design + HM).",
            "coding": "LeetCode Medium/Hard but interviewers care about systems thinking and reliability.",
            "prep_plan": [
                "2-3 weeks LC Medium/Hard + distributed systems review",
                "Design: multi-DC failover, high-availability ground station software, event pipeline",
                "Lead with MakeMyTrip multi-DC + CK high-availability ownership",
                "Prepare mission commitment talking points (why SpaceX, why Starlink)",
                "Study Kafka/Cassandra ops at scale - Starlink ground software uses similar patterns",
                "Be honest about hours expectations in HM round",
            ],
        },
    },
}
